### ISSUE TITLE
Can you update your dialog?

### ISSUE THREAD

**Issue by itexpertmaster** [aliab/Two-Step-Picker-Dialog#2]
Hi, aliab.
Nice to meet you.
Two-Step-Picker-Dialog is very helpful for me.
And I need some help with you.
Can you add image buttons on bottom?
For example, Now there are 'ok', 'dismiss' only string button.
I want image buttons on there.
Can you help me?
Thanks for your interest.

**Comment by aliab** [comment]
Hi there, 
Nice idea, I will add this feature very soon.
